### PR TITLE
Add cycle filter to !find

### PR DESCRIPTION
**Pull request by Smashman**

### CODE REVIEW

**Review by dodgepong — COMMENTED** [review]
Thanks for the catch. You will need to add a corresponding set of conditions for matching by cycle to the cardMatches function further up.

**Comment by Smashman** [comment]
Alrighty I'll pop them in tonight.

**Comment by Smashman** [comment]
I am also intending to add a link to the NetrunnerDB page for the filter currently applied. I'll do that tonight too.

**Comment by Smashman** [comment]
It is done

**Pull request merged**
