### PR TITLE
Added rotato command to ask stimbot if a card is rotating

### PR DESCRIPTION
**Pull request by muyjohno**
Called "!rotato" to avoid conflict with slackbot's "!rotate (me)?"
Searches for card named and uses card code to determine core2
legality, falling back to cycle code.

Example use:
`!rotato opus` => `"Magnum Opus" is alive and well`
`!rotato whizzard` => `"Whizzard: Master Gamer" is rotating :rip:`
`!rotato imp` => `"Imp" gets rescued by revised core set! :tada:`
`!rotato grimoire` => `"Grimoire" is rotating from revised core set! :rip:`

### CODE REVIEW

**Comment by muyjohno** [comment]
Having thought about it, maybe it should replace "rotate" and have a less dumb name :P Thoughts welcome!

**Comment by dodgepong** [comment]
I think I would rather this sort of information be pulled from the NRDB API once it gets added to there. Hard coding it feels wrong somehow.

**Comment by muyjohno** [comment]
OK sure. I guess the API will eventually contain new set details, probably in the near future, and the `[[card]]` syntax will be sufficient.

**Comment by dodgepong** [comment]
Yeah I guess my only fear is that this code will only be useful for about a month or so while people get used to the new box. I think Alsciende is adding format support to NRDB so the API may support displaying a card's legality in each format. Not sure yet, I'd like to see it when it happens.

**Pull request closed without merging**
